// Mocks generated by Mockito 5.4.6 from annotations
// in modern_turkmen/test/data/repositories/exercise/exercise_repository_remote_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i7;
import 'package:modern_turkmen/data/services/firestore/firestore_service.dart'
    as _i3;
import 'package:modern_turkmen/data/services/firestore/model/exercise/exercise_firestore_model.dart'
    as _i2;
import 'package:modern_turkmen/data/services/firestore/model/tutorial/tutorial_firestore_model.dart'
    as _i5;
import 'package:modern_turkmen/data/services/shared_preferences_service.dart'
    as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeExerciseFirestoreModel_0 extends _i1.SmartFake
    implements _i2.ExerciseFirestoreModel {
  _FakeExerciseFirestoreModel_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _Fake$ExerciseFirestoreModelCopyWith_1<$Res> extends _i1.SmartFake
    implements _i2.$ExerciseFirestoreModelCopyWith<$Res> {
  _Fake$ExerciseFirestoreModelCopyWith_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [FirestoreService].
///
/// See the documentation for Mockito's code generation for more information.
class MockFirestoreService extends _i1.Mock implements _i3.FirestoreService {
  MockFirestoreService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Stream<List<_i5.TutorialFirestoreModel>> getPublicTutorialsStream(
          String? localeName) =>
      (super.noSuchMethod(
        Invocation.method(
          #getPublicTutorialsStream,
          [localeName],
        ),
        returnValue: _i4.Stream<List<_i5.TutorialFirestoreModel>>.empty(),
      ) as _i4.Stream<List<_i5.TutorialFirestoreModel>>);

  @override
  _i4.Future<_i2.ExerciseFirestoreModel> getExerciseById(
    String? tutorialId,
    String? languageCode,
    String? exerciseId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getExerciseById,
          [
            tutorialId,
            languageCode,
            exerciseId,
          ],
        ),
        returnValue: _i4.Future<_i2.ExerciseFirestoreModel>.value(
            _FakeExerciseFirestoreModel_0(
          this,
          Invocation.method(
            #getExerciseById,
            [
              tutorialId,
              languageCode,
              exerciseId,
            ],
          ),
        )),
      ) as _i4.Future<_i2.ExerciseFirestoreModel>);

  @override
  _i4.Future<String?> getNextExerciseId({
    required String? tutorialId,
    required String? languageCode,
    required String? currentExerciseId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getNextExerciseId,
          [],
          {
            #tutorialId: tutorialId,
            #languageCode: languageCode,
            #currentExerciseId: currentExerciseId,
          },
        ),
        returnValue: _i4.Future<String?>.value(),
      ) as _i4.Future<String?>);

  @override
  _i4.Future<String?> getNextTutorialId({
    required String? tutorialId,
    required String? languageCode,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getNextTutorialId,
          [],
          {
            #tutorialId: tutorialId,
            #languageCode: languageCode,
          },
        ),
        returnValue: _i4.Future<String?>.value(),
      ) as _i4.Future<String?>);

  @override
  _i4.Future<dynamic> getTutorialById(
    String? tutorialId,
    String? languageCode,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getTutorialById,
          [
            tutorialId,
            languageCode,
          ],
        ),
        returnValue: _i4.Future<dynamic>.value(),
      ) as _i4.Future<dynamic>);

  @override
  _i4.Future<String?> getFirstExerciseId({
    required String? tutorialId,
    required String? languageCode,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getFirstExerciseId,
          [],
          {
            #tutorialId: tutorialId,
            #languageCode: languageCode,
          },
        ),
        returnValue: _i4.Future<String?>.value(),
      ) as _i4.Future<String?>);
}

/// A class which mocks [SharedPreferencesService].
///
/// See the documentation for Mockito's code generation for more information.
class MockSharedPreferencesService extends _i1.Mock
    implements _i6.SharedPreferencesService {
  MockSharedPreferencesService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<String> getPreferredLanguageCode() => (super.noSuchMethod(
        Invocation.method(
          #getPreferredLanguageCode,
          [],
        ),
        returnValue: _i4.Future<String>.value(_i7.dummyValue<String>(
          this,
          Invocation.method(
            #getPreferredLanguageCode,
            [],
          ),
        )),
      ) as _i4.Future<String>);

  @override
  void bookmarkTutorial(String? tutorialId) => super.noSuchMethod(
        Invocation.method(
          #bookmarkTutorial,
          [tutorialId],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i4.Future<void> setPreferredLanguageCode(String? languageCode) =>
      (super.noSuchMethod(
        Invocation.method(
          #setPreferredLanguageCode,
          [languageCode],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<String?> getBookmarkedTutorialId() => (super.noSuchMethod(
        Invocation.method(
          #getBookmarkedTutorialId,
          [],
        ),
        returnValue: _i4.Future<String?>.value(),
      ) as _i4.Future<String?>);

  @override
  _i4.Future<bool> isFirstLaunch() => (super.noSuchMethod(
        Invocation.method(
          #isFirstLaunch,
          [],
        ),
        returnValue: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);

  @override
  _i4.Future<void> setOnboardingCompleted() => (super.noSuchMethod(
        Invocation.method(
          #setOnboardingCompleted,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
}

/// A class which mocks [ExerciseFirestoreModel].
///
/// See the documentation for Mockito's code generation for more information.
class MockExerciseFirestoreModel extends _i1.Mock
    implements _i2.ExerciseFirestoreModel {
  MockExerciseFirestoreModel() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get id => (super.noSuchMethod(
        Invocation.getter(#id),
        returnValue: _i7.dummyValue<String>(
          this,
          Invocation.getter(#id),
        ),
      ) as String);

  @override
  String get description => (super.noSuchMethod(
        Invocation.getter(#description),
        returnValue: _i7.dummyValue<String>(
          this,
          Invocation.getter(#description),
        ),
      ) as String);

  @override
  String get example => (super.noSuchMethod(
        Invocation.getter(#example),
        returnValue: _i7.dummyValue<String>(
          this,
          Invocation.getter(#example),
        ),
      ) as String);

  @override
  List<Map<String, dynamic>> get items => (super.noSuchMethod(
        Invocation.getter(#items),
        returnValue: <Map<String, dynamic>>[],
      ) as List<Map<String, dynamic>>);

  @override
  int get orderNumber => (super.noSuchMethod(
        Invocation.getter(#orderNumber),
        returnValue: 0,
      ) as int);

  @override
  _i2.$ExerciseFirestoreModelCopyWith<_i2.ExerciseFirestoreModel>
      get copyWith => (super.noSuchMethod(
            Invocation.getter(#copyWith),
            returnValue: _Fake$ExerciseFirestoreModelCopyWith_1<
                _i2.ExerciseFirestoreModel>(
              this,
              Invocation.getter(#copyWith),
            ),
          ) as _i2.$ExerciseFirestoreModelCopyWith<_i2.ExerciseFirestoreModel>);

  @override
  Map<String, dynamic> toJson() => (super.noSuchMethod(
        Invocation.method(
          #toJson,
          [],
        ),
        returnValue: <String, dynamic>{},
      ) as Map<String, dynamic>);
}
