// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCd19Xz4spfm-di2egCTwldu5hsL9XEVhs',
    appId: '1:4636626713:android:f6c42bbdb452bb740fff88',
    messagingSenderId: '4636626713',
    projectId: 'modern-turkmen',
    storageBucket: 'modern-turkmen.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD9T8rqtLFDKgeLT9202FSP9Fc0w-TYRlU',
    appId: '1:4636626713:ios:148080e7180d994f0fff88',
    messagingSenderId: '4636626713',
    projectId: 'modern-turkmen',
    storageBucket: 'modern-turkmen.appspot.com',
    androidClientId: '4636626713-oc957prf5lte5rb6rq5t156fp0aosnde.apps.googleusercontent.com',
    iosClientId: '4636626713-gnedpdvejorlnko9nj7e97nbn3fa6c9t.apps.googleusercontent.com',
    iosBundleId: 'name.vladhomenko.modernTurkmen',
  );

}