// Mocks generated by Mockito 5.4.6 from annotations
// in modern_turkmen/test/ui/widgets/contents_table_screen_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;
import 'dart:ui' as _i7;

import 'package:mockito/mockito.dart' as _i1;
import 'package:modern_turkmen/data/repositories/language/language_repository.dart'
    as _i6;
import 'package:modern_turkmen/data/repositories/tutorial/tutorial_repository.dart'
    as _i4;
import 'package:modern_turkmen/domain/models/language.dart' as _i3;
import 'package:modern_turkmen/domain/models/tutorial/tutorial.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeTutorial_0 extends _i1.SmartFake implements _i2.Tutorial {
  _FakeTutorial_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeLanguage_1 extends _i1.SmartFake implements _i3.Language {
  _FakeLanguage_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [TutorialRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockTutorialRepository extends _i1.Mock
    implements _i4.TutorialRepository {
  MockTutorialRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Stream<List<_i2.Tutorial>> getTutorialsStream() => (super.noSuchMethod(
        Invocation.method(
          #getTutorialsStream,
          [],
        ),
        returnValue: _i5.Stream<List<_i2.Tutorial>>.empty(),
      ) as _i5.Stream<List<_i2.Tutorial>>);

  @override
  _i5.Future<String?> getNextTutorialId({required String? tutorialId}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getNextTutorialId,
          [],
          {#tutorialId: tutorialId},
        ),
        returnValue: _i5.Future<String?>.value(),
      ) as _i5.Future<String?>);

  @override
  _i5.Future<_i2.Tutorial> getTutorial(String? tutorialId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getTutorial,
          [tutorialId],
        ),
        returnValue: _i5.Future<_i2.Tutorial>.value(_FakeTutorial_0(
          this,
          Invocation.method(
            #getTutorial,
            [tutorialId],
          ),
        )),
      ) as _i5.Future<_i2.Tutorial>);

  @override
  void bookmarkTutorial(String? tutorialId) => super.noSuchMethod(
        Invocation.method(
          #bookmarkTutorial,
          [tutorialId],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i5.Future<String?> getBookmarkedTutorialId() => (super.noSuchMethod(
        Invocation.method(
          #getBookmarkedTutorialId,
          [],
        ),
        returnValue: _i5.Future<String?>.value(),
      ) as _i5.Future<String?>);
}

/// A class which mocks [LanguageRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockLanguageRepository extends _i1.Mock
    implements _i6.LanguageRepository {
  MockLanguageRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Language get currentLanguage => (super.noSuchMethod(
        Invocation.getter(#currentLanguage),
        returnValue: _FakeLanguage_1(
          this,
          Invocation.getter(#currentLanguage),
        ),
      ) as _i3.Language);

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
      ) as bool);

  @override
  _i5.Future<void> setLanguage(String? languageCode) => (super.noSuchMethod(
        Invocation.method(
          #setLanguage,
          [languageCode],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> toggleLocale() => (super.noSuchMethod(
        Invocation.method(
          #toggleLocale,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  void addListener(_i7.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListener(_i7.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}
