// Mocks generated by Mockito 5.4.6 from annotations
// in modern_turkmen/test/ui/widgets/tutorial_screen_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:mockito/mockito.dart' as _i1;
import 'package:modern_turkmen/data/repositories/exercise/exercise_repository.dart'
    as _i6;
import 'package:modern_turkmen/data/repositories/tutorial/tutorial_repository.dart'
    as _i4;
import 'package:modern_turkmen/domain/models/exercise/exercise.dart' as _i3;
import 'package:modern_turkmen/domain/models/tutorial/tutorial.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeTutorial_0 extends _i1.SmartFake implements _i2.Tutorial {
  _FakeTutorial_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeExercise_1 extends _i1.SmartFake implements _i3.Exercise {
  _FakeExercise_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [TutorialRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockTutorialRepository extends _i1.Mock
    implements _i4.TutorialRepository {
  MockTutorialRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Stream<List<_i2.Tutorial>> getTutorialsStream() => (super.noSuchMethod(
        Invocation.method(
          #getTutorialsStream,
          [],
        ),
        returnValue: _i5.Stream<List<_i2.Tutorial>>.empty(),
      ) as _i5.Stream<List<_i2.Tutorial>>);

  @override
  _i5.Future<String?> getNextTutorialId({required String? tutorialId}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getNextTutorialId,
          [],
          {#tutorialId: tutorialId},
        ),
        returnValue: _i5.Future<String?>.value(),
      ) as _i5.Future<String?>);

  @override
  _i5.Future<_i2.Tutorial> getTutorial(String? tutorialId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getTutorial,
          [tutorialId],
        ),
        returnValue: _i5.Future<_i2.Tutorial>.value(_FakeTutorial_0(
          this,
          Invocation.method(
            #getTutorial,
            [tutorialId],
          ),
        )),
      ) as _i5.Future<_i2.Tutorial>);

  @override
  void bookmarkTutorial(String? tutorialId) => super.noSuchMethod(
        Invocation.method(
          #bookmarkTutorial,
          [tutorialId],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i5.Future<String?> getBookmarkedTutorialId() => (super.noSuchMethod(
        Invocation.method(
          #getBookmarkedTutorialId,
          [],
        ),
        returnValue: _i5.Future<String?>.value(),
      ) as _i5.Future<String?>);
}

/// A class which mocks [ExerciseRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockExerciseRepository extends _i1.Mock
    implements _i6.ExerciseRepository {
  MockExerciseRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i3.Exercise> getExercise({
    required String? tutorialId,
    required String? languageCode,
    required String? exerciseId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getExercise,
          [],
          {
            #tutorialId: tutorialId,
            #languageCode: languageCode,
            #exerciseId: exerciseId,
          },
        ),
        returnValue: _i5.Future<_i3.Exercise>.value(_FakeExercise_1(
          this,
          Invocation.method(
            #getExercise,
            [],
            {
              #tutorialId: tutorialId,
              #languageCode: languageCode,
              #exerciseId: exerciseId,
            },
          ),
        )),
      ) as _i5.Future<_i3.Exercise>);

  @override
  _i5.Future<String?> getNextExerciseId({
    required String? tutorialId,
    required String? languageCode,
    required String? currentExerciseId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getNextExerciseId,
          [],
          {
            #tutorialId: tutorialId,
            #languageCode: languageCode,
            #currentExerciseId: currentExerciseId,
          },
        ),
        returnValue: _i5.Future<String?>.value(),
      ) as _i5.Future<String?>);

  @override
  _i5.Future<String?> getFirstExerciseId(String? tutorialId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getFirstExerciseId,
          [tutorialId],
        ),
        returnValue: _i5.Future<String?>.value(),
      ) as _i5.Future<String?>);
}
